Times replica
balerum03/Newyorktimes pull request #2
Opened 2020-05-19 22:36 UTC by balerum03

Implementing stickler for our project.

2020-05-21 00:48 UTC, christianotieno requested changes
# **CHANGES REQUIRED** :warning:
Hey @balerum03 & @AdesojiCodeMaster  :wave:
-
You have done a splendid job! :tada:  Keep it up.
We, however, do have some few changes to carry out before we proceed (see review comment).
##
## REQUIRED:
- [ ] the footer is not properly centred. See the difference below 👇 

| [Source](https://www.nytimes.com/2014/03/18/science/space/detection-of-waves-in-space-buttresses-landmark-theory-of-big-bang.html) | [Clone](https://raw.githack.com/balerum03/Newyorktimes/times-replica/index.html) |
|:---:|:---:|
|![footer](https://user-images.githubusercontent.com/22345961/82511279-91259800-9b15-11ea-923a-3f33f6abe771.png)|![footer-clone](https://user-images.githubusercontent.com/22345961/82511290-971b7900-9b15-11ea-92ca-33f37ea8247b.png)|
## OPTIONAL:
- [ ] You are welcome to validate your CSS using this [tool](https://jigsaw.w3.org/css-validator/validator)
- If you have any questions, let me know here or on slack and I will be glad to clarify with you. You can also reach me and connect with me on my social media or email. :eyes:
##
- When you have made the specified changes, please submit another code review. Thank you!
Happy coding :smile:
**[Christian Otieno](https://github.com/ChristianOtieno)**
[Twitter](https://twitter.com/iamchrisotieno) [linkedin](https://www.linkedin.com/in/christianotieno/) [GitLab](https://gitlab.com/christianotieno)
---
*P.S. all requested changes not marked by [OPTIONAL] or are not positive comments are **REQUIRED***

2020-05-21 15:24 UTC, balerum03 commented
Footer is now centered as requested.
![center-footer](https://user-images.githubusercontent.com/37203751/82574788-3d36a580-9b4d-11ea-9620-e47efc3f0ceb.PNG)

2020-05-22 00:13 UTC, christianotieno requested changes
## Status: Changes Required ⚠️ 
Hello, team, we are almost there, just a few tweaks and we should be done here.
- For this project to be approved, the linters must all be passing. Kindly fix that.
- As for the footer, it has not been fully implemented as expected. The footer 
should have a fixed position (it sticks to the bottom part of the screen) ([link to page](https://www.nytimes.com/2014/03/18/science/space/detection-of-waves-in-space-buttresses-landmark-theory-of-big-bang.html?_r=0)).
##
Kindly work on these changes and then submit another code review, Cheers!

2020-05-23 08:13 UTC, rammazzoti2000 requested changes
### Hello @balerum03 I am Alex your code reviewer for this project :raised_hands: 
Great job this far with this project, also implementing the changes required by the previous TSE
The are still some issue to fix before approving this project, see the comments bellow :point_down: 
## :stop_sign: Required Changes :construction: :construction_worker: 
- [ ] There is a lot of repeating codes in our CSS file, let us apply the DRY rule. For more info kindly check this [article](https://speckyboy.com/good-bad-css-practices/) ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/section/css_bad_practices_requirement.png) from Pathwright)
- [ ] The navbar should have a fixed position (it sticks to the top part of the screen) ([link to page](https://www.nytimes.com/2014/03/18/science/space/detection-of-waves-in-space-buttresses-landmark-theory-of-big-bang.html?_r=0))
- [ ] The caption for the video it should align following the width of the video, you can see that is overflowing
![image](https://user-images.githubusercontent.com/3244654/82725439-4eaeb780-9cdd-11ea-8300-55bcac7311d0.png)

- [ ] You should use [`<aside>` tag](https://www.w3schools.com/tags/tag_aside.asp) for `Editor's picks` section on the rightmost side. ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/positioning_and_floating_elements/aside_requirement.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59538403/))
### <em>Kindly fix the REQUIRED issues and send another code review request.

Cheers and Happy coding! :clap: 

Code review by Alexandru Bangau

(Feel free to contact me on slack by the handle of alexandru if you have any additional question)</em>
### :stop_sign: Status: Required Changes

2020-05-23 08:13 UTC, rammazzoti2000 commented on index.html
> +                <div class="editors-pick">
Must be an [`<aside>` tag](https://www.w3schools.com/tags/tag_aside.asp) for `Editor's picks` section on the rightmost side. ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/positioning_and_floating_elements/aside_requirement.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59538403/))

2020-05-23 08:16 UTC, rammazzoti2000 commented on index.html
> +        <div class="header-container">
The `.header-container` should be a <`nav`> tag and not a div, you should try and write proper HTML semantic code, also the navigation bar should have a fixed position (it sticks to the top of the screen)([link to the page](https://www.nytimes.com/2014/03/18/science/space/detection-of-waves-in-space-buttresses-landmark-theory-of-big-bang.html?_r=0))

2020-05-26 10:06 UTC, christianotieno approved these changes
# PROJECT APPROVED :champagne:
Excellent job on this project guys. :fireworks:  Keep it up.
##
***All the required tasks have been fulfilled in this project. I will go ahead and mark this as complete.***
- Congratulations on the splendid job @balerum03  & @AdesojiCodeMaster! :+1:
- Before we merge this, we can as well validate our CSS using this [tool](https://jigsaw.w3.org/css-validator/validator). I wish you all the very best in your next tasks 🥇 
##
Happy coding :smile:
**[Christian Otieno](https://github.com/ChristianOtieno)**
[Twitter](https://twitter.com/iamchrisotieno) [linkedin](https://www.linkedin.com/in/christianotieno/) [GitLab](https://gitlab.com/christianotieno)

2020-05-26 14:52 UTC, merged